nodes:
<<<<<<< HEAD
  - address: 172.31.71.10
    internal_address: 172.31.71.10
=======
  - address: 172.31.66.169
    internal_address: 172.31.66.169
>>>>>>> feature/msp-23
    user: ubuntu
    role: [controlplane, worker, etcd]

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

ssh_key_path: ~/.ssh/call-rancher.key

# Required for external TLS termination with
# ingress-nginx v0.22+
ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"